# Generated by Django 5.1 on 2026-06-04 19:04

import django.db.models.deletion
import payments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('payer_email', models.EmailField(max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['payer_email'], name='payments_pa_payer_e_9f1a23_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=512)),
                ('request_body_hash', models.CharField(help_text='SHA-256 hash of the request body to detect mismatched retries.', max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=20)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=payments.models.default_expires_at)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='payments_id_expires_691ca7_idx'), models.Index(fields=['status'], name='payments_id_status_0f8fb5_idx')],
            },
        ),
    ]
